package main

import "time"

type Ansprechpartner struct {
	Mandant     int       `db:"Mandant" json:"Mandant"`
	AdrNr       int       `db:"AdrNr" json:"AdrNr"`
	LaufNr      int       `db:"LaufNr" json:"LaufNr"`
	AdrNrVerk   int       `db:"AdrNr_Verk" json:"AdrNr_Verk"`
	DomizilVerk int       `db:"Domizil_Verk" json:"Domizil_Verk"`
	Anrede      string    `db:"Anrede" json:"Anrede"`
	Name        string    `db:"Name" json:"Name"`
	Vorname     string    `db:"Vorname" json:"Vorname"`
	Kuerzel     *string   `db:"Kuerzel" json:"Kuerzel"`
	Telefon     *string   `db:"Telefon" json:"Telefon"`
	Funktion    *string   `db:"Funktion" json:"Funktion"`
	Titel       *string   `db:"Titel" json:"Titel"`
	Info        *string   `db:"Info" json:"Info"`
	Briefanrede string    `db:"Briefanrede" json:"Briefanrede"`
	INS_DATE    time.Time `db:"INS_DATE" json:"INS_DATE"`
	UPD_DATE    time.Time `db:"UPD_DATE" json:"UPD_DATE"`
	INS_SABE    string    `db:"INS_SABE" json:"INS_SABE"`
	UPD_SABE    string    `db:"UPD_SABE" json:"UPD_SABE"`
	INS_SERVER  string    `db:"INS_SERVER" json:"INS_SERVER"`
}

type Domizil struct {
	Mandant        int       `db:"Mandant" json:"Mandant"`
	AdrNr          int       `db:"AdrNr" json:"AdrNr"`
	LaufNr         int       `db:"LaufNr" json:"LaufNr"`
	Sort           int       `db:"Sort" json:"Sort"`
	Art            int       `db:"Art" json:"Art"`
	ArtBezeichnung string    `db:"ArtBezeichnung" json:"ArtBezeichnung"`
	LandCode       string    `db:"LandCode" json:"LandCode"`
	Land           string    `db:"Land" json:"Land"`
	PLZ            string    `db:"PLZ" json:"PLZ"`
	Ort            string    `db:"Ort" json:"Ort"`
	Adresse        *string   `db:"Adresse" json:"Adresse"`
	TelFax         *string   `db:"TelFax" json:"TelFax"`
	Notizen        *string   `db:"Notizen" json:"Notizen"`
	Briefanrede    *string   `db:"Briefanrede" json:"Briefanrede"`
	Darstellung    string    `db:"Darstellung" json:"Darstellung"`
	INS_DATE       time.Time `db:"INS_DATE" json:"INS_DATE"`
	UPD_DATE       time.Time `db:"UPD_DATE" json:"UPD_DATE"`
	INS_SABE       string    `db:"INS_SABE" json:"INS_SABE"`
	UPD_SABE       string    `db:"UPD_SABE" json:"UPD_SABE"`
	INS_SERVER     string    `db:"INS_SERVER" json:"INS_SERVER"`
}

type Fall struct {
	Mandant                 int       `db:"Mandant" json:"Mandant"`
	FallNo                  int       `db:"FallNo" json:"FallNo"`
	FallNo_TopParent        int       `db:"FallNo_TopParent" json:"FallNo_TopParent"`
	FallNo_Parent           int       `db:"FallNo_Parent" json:"FallNo_Parent"`
	Fall_Level              int       `db:"Fall_Level" json:"Fall_Level"`
	Owner                   string    `db:"Owner" json:"Owner"`
	FallBezeichnung         *string   `db:"FallBezeichnung" json:"FallBezeichnung"`
	FallInfo                *string   `db:"FallInfo" json:"FallInfo"`
	Ablage                  *string   `db:"Ablage" json:"Ablage"`
	Name                    string    `db:"Name" json:"Name"`
	HSatz                   float64   `db:"HSatz" json:"HSatz"`
	FKPreis                 float64   `db:"FKPreis" json:"FKPreis"`
	KmPreis                 float64   `db:"KmPreis" json:"KmPreis"`
	Interessewert           float64   `db:"Interessewert" json:"Interessewert"`
	Status                  string    `db:"Status" json:"Status"`
	Sprache                 int       `db:"Sprache" json:"Sprache"`
	TypRechnung             int       `db:"TypRechnung" json:"TypRechnung"`
	Waehrung                string    `db:"Waehrung" json:"Waehrung"`
	Intern                  int       `db:"Intern" json:"Intern"`
	Fibu                    int       `db:"Fibu" json:"Fibu"`
	Formular                int       `db:"Formular" json:"Formular"`
	MWStCode                int       `db:"MWStCode" json:"MWStCode"`
	Gesperrt                int       `db:"Gesperrt" json:"Gesperrt"`
	Abgerechnet             int       `db:"Abgerechnet" json:"Abgerechnet"`
	FixHonorar              int       `db:"FixHonorar" json:"FixHonorar"`
	FallBeginn              time.Time `db:"FallBeginn" json:"FallBeginn"`
	Standort                int       `db:"Standort" json:"Standort"`
	SRechFaktInt            int       `db:"SRechFaktInt" json:"SRechFaktInt"`
	Budget                  float64   `db:"Budget" json:"Budget"`
	ProjectMode             int       `db:"ProjectMode" json:"ProjectMode"`
	FallNo_Alt              *string   `db:"FallNo_Alt" json:"FallNo_Alt"`
	INS_DATE                time.Time `db:"INS_DATE" json:"INS_DATE"`
	UPD_DATE                time.Time `db:"UPD_DATE" json:"UPD_DATE"`
	INS_SABE                string    `db:"INS_SABE" json:"INS_SABE"`
	UPD_SABE                string    `db:"UPD_SABE" json:"UPD_SABE"`
	INS_SERVER              string    `db:"INS_SERVER" json:"INS_SERVER"`
	SubprojectsInheritOwner int       `db:"SubprojectsInheritOwner" json:"SubprojectsInheritOwner"`
	EBilling                *string   `db:"eBilling" json:"eBilling"`
}

type Subjekt struct {
	Mandant     int       `db:"Mandant" json:"Mandant"`
	AdrNr       int       `db:"AdrNr" json:"AdrNr"`
	Status      string    `db:"Status" json:"Status"`
	Art         string    `db:"Art" json:"Art"`
	Anrede      *string   `db:"Anrede" json:"Anrede"`
	Titel       *string   `db:"Titel" json:"Titel"`
	Funktion    *string   `db:"Funktion" json:"Funktion"`
	Name1       string    `db:"Name1" json:"Name1"`
	Name2       *string   `db:"Name2" json:"Name2"`
	Sprache     int       `db:"Sprache" json:"Sprache"`
	Geschlecht  int       `db:"Geschlecht" json:"Geschlecht"`
	Briefanrede string    `db:"Briefanrede" json:"Briefanrede"`
	Notizen     *string   `db:"Notizen" json:"Notizen"`
	INS_DATE    time.Time `db:"INS_DATE" json:"INS_DATE"`
	UPD_DATE    time.Time `db:"UPD_DATE" json:"UPD_DATE"`
	INS_SABE    string    `db:"INS_SABE" json:"INS_SABE"`
	UPD_SABE    string    `db:"UPD_SABE" json:"UPD_SABE"`
	INS_SERVER  string    `db:"INS_SERVER" json:"INS_SERVER"`
}

type SubjektStruct struct {
	Mandant1     int     `db:"Mandant_1" json:"Mandant_1"`
	AdrNr1       int     `db:"AdrNr_1" json:"AdrNr_1"`
	Art          int     `db:"Art" json:"Art"`
	Code         int     `db:"Code" json:"Code"`
	Mandant2     int     `db:"Mandant_2" json:"Mandant_2"`
	Nr2          int     `db:"Nr_2" json:"Nr_2"`
	Nr3          int     `db:"Nr_3" json:"Nr_3"`
	Nr4          int     `db:"Nr_4" json:"Nr_4"`
	Beschreibung *string `db:"Beschreibung" json:"Beschreibung"`
	INS_SERVER   string  `db:"INS_SERVER" json:"INS_SERVER"`
}

type LogEintrag struct {
	Mandant              int        `db:"Mandant" json:"Mandant"`
	LogNo                int        `db:"LogNo" json:"LogNo"`
	Del                  int        `db:"Del" json:"Del"`
	Fall                 int        `db:"Fall" json:"Fall"`
	ColorTyp             int        `db:"ColorTyp" json:"ColorTyp"`
	Owner                int        `db:"Owner" json:"Owner"`
	Status               int        `db:"Status" json:"Status"`
	Fibu                 int        `db:"Fibu" json:"Fibu"`
	DebStatus            int        `db:"DebStatus" json:"DebStatus"`
	DebDetail            int        `db:"DebDetail" json:"DebDetail"`
	MWStCode             int        `db:"MWStCode" json:"MWStCode"`
	FIBUTransfer         int        `db:"FIBUTransfer" json:"FIBUTransfer"`
	FIBUKtoS             int        `db:"FIBUKtoS" json:"FIBUKtoS"`
	FIBUKtoH             int        `db:"FIBUKtoH" json:"FIBUKtoH"`
	LogDatum             time.Time  `db:"LogDatum" json:"LogDatum"`
	DSPLY_Typ            *string    `db:"DSPLY_Typ" json:"DSPLY_Typ"`
	DSPLY_Zusatz         *string    `db:"DSPLY_Zusatz" json:"DSPLY_Zusatz"`
	LogText              *string    `db:"LogText" json:"LogText"`
	LogTyp               int        `db:"LogTyp" json:"LogTyp"`
	DokumentName         *string    `db:"DokumentName" json:"DokumentName"`
	PathName             *string    `db:"PathName" json:"PathName"`
	HON_ZeitVon          *float64   `db:"HON_ZeitVon" json:"HON_ZeitVon"`
	HON_ZeitBis          *float64   `db:"HON_ZeitBis" json:"HON_ZeitBis"`
	HON_Std              *float64   `db:"HON_Std" json:"HON_Std"`
	HON_Satz             *float64   `db:"HON_Satz" json:"HON_Satz"`
	HON_Total            *float64   `db:"HON_Total" json:"HON_Total"`
	AUS_Total            *float64   `db:"AUS_Total" json:"AUS_Total"`
	AUS_Typ              *int       `db:"AUS_Typ" json:"AUS_Typ"`
	AUS_AnzahlFK         *float64   `db:"AUS_AnzahlFK" json:"AUS_AnzahlFK"`
	AUS_FKPreis          *float64   `db:"AUS_FKPreis" json:"AUS_FKPreis"`
	AUS_Km               *float64   `db:"AUS_Km" json:"AUS_Km"`
	AUS_KmPreis          *float64   `db:"AUS_KmPreis" json:"AUS_KmPreis"`
	NOT_Text             *string    `db:"NOT_Text" json:"NOT_Text"`
	FRI_Erledigt         *int       `db:"FRI_Erledigt" json:"FRI_Erledigt"`
	FRI_Tage             *float64   `db:"FRI_Tage" json:"FRI_Tage"`
	TDO_Erledigt         *int       `db:"TDO_Erledigt" json:"TDO_Erledigt"`
	TDO_Tage             *float64   `db:"TDO_Tage" json:"TDO_Tage"`
	ZAL_Total            *float64   `db:"ZAL_Total" json:"ZAL_Total"`
	ZAL_VorausZ          *int       `db:"ZAL_VorausZ" json:"ZAL_VorausZ"`
	TER_Termin           *float64   `db:"TER_Termin" json:"TER_Termin"`
	TER_Erledigt         *int       `db:"TER_Erledigt" json:"TER_Erledigt"`
	TER_VorMahnzeit      *float64   `db:"TER_VorMahnzeit" json:"TER_VorMahnzeit"`
	TER_Mahnen           *int       `db:"TER_Mahnen" json:"TER_Mahnen"`
	AKG_Betrag           *float64   `db:"AKG_Betrag" json:"AKG_Betrag"`
	REC_DatumVon         *string    `db:"REC_DatumVon" json:"REC_DatumVon"`
	REC_DatumBis         *string    `db:"REC_DatumBis" json:"REC_DatumBis"`
	REC_Total1           *float64   `db:"REC_Total1" json:"REC_Total1"`
	REC_Zahlungen        *float64   `db:"REC_Zahlungen" json:"REC_Zahlungen"`
	REC_Auslagen         *float64   `db:"REC_Auslagen" json:"REC_Auslagen"`
	REC_Std              *float64   `db:"REC_Std" json:"REC_Std"`
	REC_HonorarStd       *float64   `db:"REC_HonorarStd" json:"REC_HonorarStd"`
	REC_Honorar          *float64   `db:"REC_Honorar" json:"REC_Honorar"`
	REC_MWSt             *float64   `db:"REC_MWSt" json:"REC_MWSt"`
	REC_Total2           *float64   `db:"REC_Total2" json:"REC_Total2"`
	REC_Entwurf          *int       `db:"REC_Entwurf" json:"REC_Entwurf"`
	REC_Zwischenrechnung *int       `db:"REC_Zwischenrechnung" json:"REC_Zwischenrechnung"`
	MAN_Betrag           *float64   `db:"MAN_Betrag" json:"MAN_Betrag"`
	MAN_Frist            *time.Time `db:"MAN_Frist" json:"MAN_Frist"`
	MAN_Art              *int       `db:"MAN_Art" json:"MAN_Art"`
	MAN_LastRef          *string    `db:"MAN_LastRef" json:"MAN_LastRef"`
	FXH_No               *int       `db:"FXH_No" json:"FXH_No"`
	FXH_Betrag           *float64   `db:"FXH_Betrag" json:"FXH_Betrag"`
	FXH_AHV              *int       `db:"FXH_AHV" json:"FXH_AHV"`
	FRG_Betrag           *float64   `db:"FRG_Betrag" json:"FRG_Betrag"`
	INS_DATE             time.Time  `db:"INS_DATE" json:"INS_DATE"`
	UPD_DATE             time.Time  `db:"UPD_DATE" json:"UPD_DATE"`
	INS_SABE             *string    `db:"INS_SABE" json:"INS_SABE"`
	UPD_SABE             *string    `db:"UPD_SABE" json:"UPD_SABE"`
	INS_SERVER           *string    `db:"INS_SERVER" json:"INS_SERVER"`
}
